import Link from "next/link";

export const metadata = { title: "Terms of Service — Magic Mint" };

// PLACEHOLDER — this is scaffolding so the ToS acceptance gate and footer links
// resolve. Replace the body with final Terms of Service reviewed by counsel
// before launch (the deepfake-prohibition clause below is required by CCBill).
export default function TermsPage() {
  return (
    <main style={{ maxWidth: 760, margin: "0 auto", padding: "64px 24px", color: "#e8e8ea", fontFamily: "system-ui, sans-serif", lineHeight: 1.6 }}>
      <Link href="/" style={{ color: "#7aa2ff", fontSize: 14 }}>← Magic Mint</Link>
      <h1 style={{ fontSize: 32, marginTop: 16 }}>Terms of Service</h1>
      <p style={{ color: "#c9a227", background: "rgba(201,162,39,0.1)", border: "1px solid rgba(201,162,39,0.3)", padding: "10px 14px", borderRadius: 8, fontSize: 14 }}>
        Draft placeholder — must be replaced with final, counsel-reviewed Terms before launch.
      </p>

      <h2>1. Eligibility</h2>
      <p>You must be at least 18 years old to use Magic Mint. By using the service you represent that you are 18 or older.</p>

      <h2>2. AI-Generated Content</h2>
      <p>All media produced through Magic Mint is generated by artificial intelligence and is synthetic. It does not depict real events.</p>

      <h2>3. Prohibited Use — Deepfakes</h2>
      <p>
        You may not use Magic Mint to generate "deepfake" images or video, or any sexual or
        explicit content depicting the likeness of a real, identifiable person without that
        person's verifiable consent. This is strictly prohibited.
      </p>

      <h2>4. Other Prohibited Content</h2>
      <p>
        You may not generate content depicting or implying minors in any scenario; non-consensual,
        incest, bestiality, violent/snuff, or other content prohibited by applicable law or card-brand
        rules. See the <Link href="/acceptable-use" style={{ color: "#7aa2ff" }}>Acceptable Use Policy</Link> for the full list.
      </p>

      <h2>5. Enforcement</h2>
      <p>
        Violations result in immediate account termination and, where required by law, reporting to
        the appropriate authorities (including the NCMEC CyberTipline for suspected child sexual
        abuse material).
      </p>
    </main>
  );
}
