import Link from "next/link";
import LegalPage from "@/components/LegalPage";

export const metadata = { title: "Terms of Service — Eromify" };

// PLACEHOLDER — scaffolding so the ToS gate and footer links resolve. Replace
// with final Terms reviewed by counsel before launch (the deepfake-prohibition
// clause below is required by CCBill).
export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <h2>1. Eligibility</h2>
      <p>You must be at least 18 years old to use Eromify. By using the service you represent that you are 18 or older.</p>

      <h2>2. AI-Generated Content</h2>
      <p>All media produced through Eromify is generated by artificial intelligence and is synthetic. It does not depict real events.</p>

      <h2>3. Prohibited Use — Deepfakes</h2>
      <p>
        You may not use Eromify to generate "deepfake" images or video, or any sexual or
        explicit content depicting the likeness of a real, identifiable person without that
        person's verifiable consent. This is strictly prohibited.
      </p>

      <h2>4. Other Prohibited Content</h2>
      <p>
        You may not generate content depicting or implying minors in any scenario; non-consensual,
        incest, bestiality, violent/snuff, or other content prohibited by applicable law or card-brand
        rules. See the <Link href="/acceptable-use" style={{ color: "#7aa2ff" }}>Acceptable Use Policy</Link> for the full list.
      </p>

      <h2>5. Enforcement</h2>
      <p>
        Violations result in immediate account termination and, where required by law, reporting to
        the appropriate authorities (including the NCMEC CyberTipline for suspected child sexual
        abuse material).
      </p>
    </LegalPage>
  );
}
